PR feedback

diff --git a/.github/actions/generate-production-release/action.yml b/.github/actions/generate-production-release/action.yml
--- a/.github/actions/generate-production-release/action.yml
+++ b/.github/actions/generate-production-release/action.yml
@@ -1,13 +1,16 @@
 name: 'Generate production release'
 description: 'Given a QA pre release tag, will generate production ready release for the tagged version'
 inputs:
+  tag-name:
+    description: Tag name - The name for the tag that will be given to this release.
+    required: true
   title:
-    description: Release title - The title that will be given to this pre-release.
+    description: Release title - The title that will be given to this release.
     required: true
 outputs:
   generated-release-tag:
     description: "The generated release tag"
-    value: ${{ steps.get_release_tag.outputs.generated-tag }}
+    value: ${{ inputs.tag-name }}
 
 runs:
   using: "composite"
@@ -17,32 +20,24 @@ runs:
       with:
         node-version: '14.x'
 
-    # Get release tag
-    - name: Get release tag
-      run: npm run get-release-tag
+    - name: Validate ref type
+      shell: bash
       env:
-        REF: ${{  github.ref_name }}
-      working-directory: ${{ github.action_path }}
-      shell: bash
-      id: get_release_tag
-
-    - run: echo ${{ steps.get_release_tag.outputs.generated-tag }}
-      shell: bash
-
-    - name: "Check release notes file exists"
-      uses: andstor/file-existence-action@v2.0.0
-      with:
-        files: "release-notes/${{ steps.get_release_tag.outputs.generated-tag }}.md"
-        fail: true
+        REF_TYPE: ${{ github.ref_type }}
+      run: |
+        if [ $REF_TYPE != 'tag' ] 
+        then  
+          echo "::error::ERROR - The ref provided is not a tag."
+          exit 1
+        fi
 
     # Create a release
     - name: Create a release
       uses: ncipollo/release-action@v1.12.0
       with:
         commit: ${{ github.sha }}
-        tag: ${{ steps.get_release_tag.outputs.generated-tag }}
+        tag: ${{ inputs.tag-name }}
         name: ${{ inputs.title }}
-        bodyFile: "release-notes/${{ steps.get_release_tag.outputs.generated-tag }}.md"
+        body: "TO-DO"
         prerelease: false
-        # allowUpdates: true ## do we want to allow "updates" to a release?
       id: create_release
