Alejandro/test rigor/regression tests workflow 4 (#2685)
* new workflow

* renaming

* changes

* testing better message

diff --git a/.github/workflows/run-testrigor-regression-tests.yml b/.github/workflows/run-testrigor-regression-tests.yml
--- a/.github/workflows/run-testrigor-regression-tests.yml
+++ b/.github/workflows/run-testrigor-regression-tests.yml
@@ -75,11 +75,20 @@ jobs:
       - name: Run Test Rigor Regression Tests
         shell: bash
         run: |
-          curl -X POST \
+          task_response=$( curl -X POST \
           -H 'Content-type: application/json' \
           -H 'auth-token: ${{env.TEST_RIGOR_AUTH_TOKEN}}' \
           --data '{"forceCancelPreviousTesting":true,"labels": [ "${{inputs.section}}"]}' \
-          https://api.testrigor.com/api/v1/apps/${{env.TEST_RIGOR_SUITE_ID}}/retest
+          https://api.testrigor.com/api/v1/apps/${{env.TEST_RIGOR_SUITE_ID}}/retest)
+          task_id=$(echo "$task_response" | jq -r '.taskId')
+          
+          # Check if task_id is defined
+          if [[ -z "$task_id" || "$task_id" == "null" ]]; then
+            echo "Failed to start the test. Task response: $task_response"
+            exit 1
+          fi
+
+          echo "Test started with taskId: $task_id"
 
           sleep 10
 
@@ -125,6 +134,6 @@ jobs:
         uses: slackapi/slack-github-action@v1.14.0
         with:
           channel-id: ${{ env.ASELO_DEPLOYS_CHANNEL_ID }}
-          slack-message: "`[testRigor]` Regression Tests (${{ inputs.section }}) for environment `${{ inputs.environment_code }}` of ${{ github.ref_type }} `${{ github.ref_name }}` requested by `${{ github.triggering_actor }}` completed using workflow `${{ github.workflow }}` with SHA ${{ github.sha }} :rocket:."
+          slack-message: "`[testRigor]` Regression Tests (${{ inputs.section }}) for environment `${{ inputs.environment_code }}` of ${{ github.ref_type }} `${{ github.ref_name }}` requested by `${{ github.triggering_actor }}` completed using workflow `${{ github.workflow }}` with SHA ${{ github.sha }} :rocket:. \n Test Results: [View Test Rigor Run](https://app.testrigor.com/${{ env.TEST_RIGOR_SUITE_ID }}/runs/$task_id)"
         env:
           SLACK_BOT_TOKEN: ${{ env.GITHUB_ACTIONS_SLACK_BOT_TOKEN }}
