Alejandro/test rigor/regression tests workflow 6 (#2687)
* new workflow

* renaming

* changes

* testing better message

* testing udpate

* removing check loop and adding link

diff --git a/.github/workflows/run-testrigor-smoke-tests.yml b/.github/workflows/run-testrigor-smoke-tests.yml
--- a/.github/workflows/run-testrigor-smoke-tests.yml
+++ b/.github/workflows/run-testrigor-smoke-tests.yml
@@ -61,56 +61,27 @@ jobs:
       - name: Run Test Rigor Smoke Tests
         shell: bash
         run: |
-          curl -X POST \
+          task_response=$(curl -X POST \
           -H 'Content-type: application/json' \
           -H 'auth-token: ${{env.TEST_RIGOR_AUTH_TOKEN}}' \
           --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
-          https://api.testrigor.com/api/v1/apps/${{env.TEST_RIGOR_SUITE_ID}}/retest
+          https://api.testrigor.com/api/v1/apps/${{env.TEST_RIGOR_SUITE_ID}}/retest)
+          task_id=$(echo "$task_response" | jq -r '.taskId')
+          
+          # Check if task_id is defined
+          if [[ -z "$task_id" || "$task_id" == "null" ]]; then
+            echo "Failed to start the test. Task response: $task_response"
+            exit 1
+          fi
+          # Set task_id as an environment variable for the next steps
+          echo "TASK_ID=$task_id" >> $GITHUB_ENV
 
-          sleep 10
-
-          while true
-          do
-            echo " "
-            echo "==================================="
-            echo " Checking TestRigor retest"
-            echo "==================================="
-            response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/${{env.TEST_RIGOR_SUITE_ID}}/status' -H 'auth-token: ${{env.TEST_RIGOR_AUTH_TOKEN}}' -H 'Accept: application/json')
-            code=$(echo "$response" | grep HTTP |  awk '{print $2}')
-            body=$(echo "$response" | sed -n '/{/,/}/p')
-            echo "Status code: " $code
-            echo "Response: " $body
-            case $code in
-              4*|5*)
-                # 400 or 500 errors
-                echo "Error calling API"
-                exit 1
-                ;;
-              200)
-                # 200: successfully finished
-                echo "Test finished successfully"
-                exit 0
-                ;;
-              227|228)
-                # 227: New - 228: In progress
-                echo "Test is not finished yet"
-                ;;
-              230)
-                # 230: Failed
-                echo "Test finished but failed"
-                exit 1
-                ;;
-              *)
-                echo "Unknown status"
-                exit 1
-              esac
-            sleep 10
-          done
+          echo "Test started with taskId: $task_id"
       - name: Slack Aselo channel
         id: slack
         uses: slackapi/slack-github-action@v1.14.0
         with:
           channel-id: ${{ env.ASELO_DEPLOYS_CHANNEL_ID }}
-          slack-message: "`[testRigor]` Smoke Tests for environment `${{ inputs.environment_code }}` of ${{ github.ref_type }} `${{ github.ref_name }}` requested by `${{ github.triggering_actor }}` completed using workflow `${{ github.workflow }}` with SHA ${{ github.sha }} :rocket:."
+          slack-message: "`[testRigor]` Smoke Tests for environment `${{ inputs.environment_code }}` requested by `${{ github.triggering_actor }}` started using workflow `${{ github.workflow }}` :rocket:. \n Test Run: https://app.testrigor.com/test-suites/${{ env.TEST_RIGOR_SUITE_ID }}/runs/${{ env.TASK_ID }}"
         env:
           SLACK_BOT_TOKEN: ${{ env.GITHUB_ACTIONS_SLACK_BOT_TOKEN }}
